### ISSUE TITLE
CPE not detecting Fiducial List 

### ISSUE THREAD

**Issue by Kaelasha** [mnarizzano/SEEGA#107]
Hi. My Slicer (5.0.3) CPE module shows only "Fiducial List=None" despite my having loaded a text file with electrode locations and a pre-processed post-implant CT volume into the Slicer scene.
The electrode position text file is in the form of [A, x, y, z; A1, x, y, z; Bm xm ym z; B1, x, y, z; ...] and is loaded as a table in the Slicer scene.  I created the electrode position text file manually in Slicer by visually checking electrode tip and surface coordinates.

**Comment by mnarizzano** [comment]
Dear Kaelasha,
thank you for your help.

I just downloaded sl;icer 5.3 and a fresh SEEGA framework. I created a new markups fiducial point list and it was showing in the fiducial list menu. I have also loaded a fiducial list file from my HD and again it was showing correctly. So I can not replicate your issue.

Just to be sure, the CPE is only showing murkups, so you can check if your points are listed in the markup module (Markups). If it is not showed what you loaded is not just a markup list.

If still not working, please can you send me more information and eventually the fiducial list file, and the exact procedure yuo have used in order to replicate the problem?
all the best
mn

**Comment by Kaelasha** [comment]
Thanks for your response. I have since realized that this was an issue with my electrode position markup file not loading properly into Slicer, eg not a SEEGA issue.

**Comment by mnarizzano** [comment]
perfect! issues closed
