### ISSUE TITLE
Reload the configuration files 

### ISSUE THREAD

**Issue by mnarizzano** [mnarizzano/SEEGA#19]
Please, add a button in the contact position estimator, in the configuration canvas, that reload the configuration files without restarting slicer.

**Comment by mosenco** [comment]
As requested i added a button to reload the right configuration file.

Also in the function `ondeetoTB()` the new file overwrite the `slicer.modules.ContactPositionEstimatorInstance.deetoExecutablePath` which is no required, because at start the module see our OS and decide automatically which file use for the configuration. There was also a "bug" where, if no file is selected, we lose focus on `slicer.modules.ContactPositionEstimatorInstance.deetoExecutablePath`. I solved with an `if else` 41002a9
