### ISSUE TITLE
Saving contactpoint coordinates in single file

### ISSUE THREAD

**Issue by azian19360** [mnarizzano/SEEGA#26]
Dear mister Narizzano,

Thank you for developing SEEGA and all the service that comes with it. 

By this way I would like to inform for a possibility to provide a way or option in the application to save the coordinates for every contactpoint per electrode in a single file, excel or matlab. 

This would make it easier to compare several patients in a one study based on their SEEG-results and to keep that up in a database. 

Looking forward to your response.

Kind regards,
Zian

**Comment by mnarizzano** [comment]
Dear Zian,
thank you for your interest in SEEGA. 
I am not sure I have understood your question correctly.
Did you mean 
1) one file for each contact  formatted in excel/matlab? or
2) one file for all the contacts formatted in excel/matlab?

thank you
Massimo

**Comment by azian19360** [comment]
Dear mister Narizzano,

I meant one file for alle the contacts formatted in excel/Matlab. So option 2. This way I could get an overview of all the coordinates of the marked contactpoints in one sheet.

Kind regards,
Zian

Op 10 okt. 2017 11:00 a.m. schreef Massimo Narizzano <notifications@github.com>:

Dear Zian,
thank you for your interest in SEEGA.
I am not sure I have understood your question correctly.
Did you mean

  1.  one file for each contact formatted in excel/matlab? or
  2.  one file for all the contacts formatted in excel/matlab?

thank you
Massimo

**Comment by mnarizzano** [comment]
Dear Zian,
in this case it is already done! :)
Follows these steps:

XLS (openoffice)
1) Save the recon file from slicer (save)
2) run openoffice
3) open file 
4) select your recon.fcsv
5) Text import should be, then select as separator tab/comma/semicolon/space
6) Select as text delimiter single quote
7) then select ok

The formatting is not perfect but it is ok. It should work both for openoffice and excel. If you 
are using excel please let me know if it works fine

Just a suggestion:
For a better fomatting, since the number of brain zones detected is different for each contact, it is preferable to execute Brain Zone detection as last computation (I.e. do GMPI computation before the BZ detection).

MATLAB
Since the recon.fcsv (file saved by 3D slicer) is a formatted text file can be easily read by  matlab.

**Comment by azian19360** [comment]
Dear mister Narizzano,

Thank you for your reply. I have tried out your suggestion and it worked out well to get the coordinates viewedin Excel. I got my overview now.
Thank you very much for your help.

Kind regards,
Zian.
________________________________
Van: Massimo Narizzano [notifications@github.com]
Verzonden: dinsdag 10 oktober 2017 12:00
Aan: mnarizzano/SEEGA
CC: Zian, Ahmed; Author
Onderwerp: Re: [mnarizzano/SEEGA] Saving contactpoint coordinates in single file (#26)


Dear Zian,
in this case it is already done! :)
Follows these steps:

XLS (openoffice)

  1.  Save the recon file from slicer (save)
  2.  run openoffice
  3.  open file
  4.  select your recon.fcsv
  5.  Text import should be, then select as separator tab/comma/semicolon/space
  6.  Select as text delimiter single quote
  7.  then select ok

The formatting is not perfect but it is ok. It should work both for openoffice and excel. If you
are using excel please let me know if it works fine

Just a suggestion:
For a better fomatting, since the number of brain zones detected is different for each contact, it is preferable to execute Brain Zone detection as last computation (I.e. do GMPI computation before the BZ detection).

MATLAB
Since the recon.fcsv (file saved by 3D slicer) is a formatted text file can be easily read by matlab.

**Comment by mnarizzano** [comment]
Dear Zian,
I am happy that your problem is solved.
I am going to close the issue.
If you have any problem feel free to contact us.
All the best
Massimo
