### ISSUE TITLE
slicer.util.MRMLNodeNotFoundException: could not find nodes in the scene by name or id 'recon'

### ISSUE THREAD

**Issue by abiii-daniele** [mnarizzano/SEEGA#71]
Finalizer.py", line 97, in setup
    badChannelList.setCurrentNode(slicer.util.getNode('recon'))
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 1474, in getNode
    raise MRMLNodeNotFoundException("could not find nodes in the scene by name or id '%s'" % (pattern if (isinstance(pattern, str)) else ""))

**Comment by abiii-daniele** [comment]
fix getNode error, following the advice at site: https://discourse.slicer.org/t/slicer-util-mrmlnodenotfoundexception-could-not-find-nodes-in-the-scene-by-name-or-id-error/14135 #72

**Comment by mosenco** [comment]
Instead of using `slicer.util.getNode()`, i used `slicer.mrmlScene.GetFirstNodeByName()` to solve the problem   

ref: [https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide#Slicer_4.9:_slicer.util.getNode.28.29_raises_exception_if_node_not_found](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide#Slicer_4.9:_slicer.util.getNode.28.29_raises_exception_if_node_not_found)

**Comment by mosenco** [comment]
4ea86d3
